server:
  port: 9001

spring:
  application:
    name: leadnews-user

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.6.117:3306/leadnews_user?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: weiwei1216*

# 打印sql语句，方便调试
logging:
  level:
    com.heima.user: debug

# mybatis-plus 配置
mybatis-plus:
  # 设置 Mapper 接口所对应的 XML 文件位置，如果你在 Mapper 接口中有自定义方法，需要进行该配置
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.user.pojos
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true

# 设置RSA私钥地址
leadnews:
  jwt:
    privateKeyPath: /Users/mac/Desktop/News/passwd/id-rsa
    expire: 240
